---
- name: ansible-role-configure_firewall
- name: ansible-role-configure_sshd
- name: ansible-role-copy_etc_issue
- name: ansible-role-configure_sudo
- name: ansible-role-set_hostname
- name: ansible-role-update_pkgs
- name: ansible-role-install_fail2ban
- name: ansible-role-auto_pkg_updates
- name: ansible-role-setup_users
